Ofir/add context getters setters
blinkops/plugin-sdk pull request #2
Opened 2021-05-19 07:15 UTC by itsofirblink

2021-05-19 17:38 UTC, danielsblinkops requested changes

2021-05-19 17:38 UTC, danielsblinkops commented on plugin/action_context.go
> +
Why new line

2021-05-19 17:38 UTC, danielsblinkops commented on plugin/action_context.go
> +	value, err := context.Get(key, ctx.internalContext)
Just create a context object which has a .Get() method.
right now its a wierd usage

2021-05-19 17:38 UTC, danielsblinkops commented on plugin/context/engine.go
> +func getMap(parameter string, context map[string]interface{}) map[string]interface{} {
What is getMap? What is the map

2021-05-19 17:38 UTC, danielsblinkops commented on plugin/context/engine.go
> +func getMap(parameter string, context map[string]interface{}) map[string]interface{} {
What is parameter, make names more indicative, doc each function

2021-05-19 17:38 UTC, danielsblinkops commented on plugin/context/engine.go
> +	"errors"
I think u just make an context class, and have the context map as a member

2021-05-19 17:38 UTC, danielsblinkops commented on plugin/context/engine.go
> +	if !strings.Contains(parameter, ".") {
Dont double scan here, do 
	location := strings.Split(parameter, ".")
	if len(location) ==0 { return nil}
	
Also change location to a more indicative name, line innerObjectKey

2021-05-19 17:38 UTC, danielsblinkops commented on plugin/context/engine.go
> +	return internalContext.(map[string] interface{})
Do safe casts plsz

2021-05-19 17:38 UTC, danielsblinkops commented on plugin/context/engine.go
> +func getIterator(parameter string, create bool, context map[string]interface{}) (map[string]interface{}, error) {
You dont return any iterator here... its just a map

2021-05-19 17:38 UTC, danielsblinkops commented on plugin/context/engine.go
> +func getIterator(parameter string, create bool, context map[string]interface{}) (map[string]interface{}, error) {
Also better naming for params, the fuck is create

2021-05-19 17:38 UTC, danielsblinkops commented on plugin/context/engine.go
> +	for i := 1; i < depth; i++ {
Move to outside function which an indiciative name, like resolveInnerItems or something

2021-05-20 06:56 UTC, itsofirblink commented on plugin/context/engine.go
> +func getMap(parameter string, context map[string]interface{}) map[string]interface{} {
Thats the start of the structure, we need to make sure the users can't access something that's not created yet,
we will have `inputs` and `variables` thats the map that you will get access to by `getMap` changed the name to `getInnerContext`

2021-05-20 06:57 UTC, itsofirblink commented on plugin/context/engine.go
> +func getMap(parameter string, context map[string]interface{}) map[string]interface{} {
Changed to `key` and moved the function to the `ActionContext`

2021-05-20 06:57 UTC, itsofirblink commented on plugin/context/engine.go
> +	"errors"
I'm overriding your functions :)

2021-05-20 07:00 UTC, itsofirblink commented on plugin/context/engine.go
> +	if !strings.Contains(parameter, ".") {
Done :)

2021-05-20 07:01 UTC, itsofirblink commented on plugin/context/engine.go
> +	return internalContext.(map[string] interface{})
Will do :)

2021-05-23 05:31 UTC, merged